"""add is_super_admin to user

Revision ID: 3175258add5a
Revises: new_revision_id_here
Create Date: 2026-03-28 15:48:28.934654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3175258add5a'
down_revision: Union[str, Sequence[str], None] = 'new_revision_id_here'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1️⃣ permissions fix (already fine)
    op.alter_column('permissions', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ---------------------------
    # 2️⃣ PROJECTS FIX
    # ---------------------------
    op.add_column('projects', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.execute("UPDATE projects SET tenant_id = 1")
    op.alter_column('projects', 'tenant_id', nullable=False)
    op.create_foreign_key(None, 'projects', 'tenants', ['tenant_id'], ['id'])

    # ---------------------------
    # 3️⃣ ROLES FIX
    # ---------------------------
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ---------------------------
    # 4️⃣ TASKS FIX (IMPORTANT)
    # ---------------------------
    op.add_column('tasks', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.execute("UPDATE tasks SET tenant_id = 1")
    op.alter_column('tasks', 'tenant_id', nullable=False)

    op.add_column('tasks', sa.Column('assigned_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'users', ['assigned_user_id'], ['id'])

    # ---------------------------
    # 5️⃣ SUPER ADMIN FIX (IMPORTANT)
    # ---------------------------
    op.add_column('users', sa.Column('is_super_admin', sa.Boolean(), nullable=True))

    # Set all existing users as False
    op.execute("UPDATE users SET is_super_admin = FALSE")

    # Make it NOT NULL
    op.alter_column('users', 'is_super_admin', nullable=False)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_super_admin')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'assigned_user_id')
    op.drop_column('tasks', 'tenant_id')
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'tenant_id')
    op.alter_column('permissions', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
