"""add is_verified column

Revision ID: 6ea9109633eb
Revises: 3175258add5a
Create Date: 2026-03-30 21:21:36.946727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ea9109633eb'
down_revision: Union[str, Sequence[str], None] = '3175258add5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_codes', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.alter_column('users', 'is_super_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_super_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('otp_codes', 'is_verified')
    # ### end Alembic commands ###
