"""added project_id to task and relationship

Revision ID: e76b227c9412
Revises: c06fe05d59c9
Create Date: 2026-02-24 22:01:47.649285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e76b227c9412'
down_revision: Union[str, Sequence[str], None] = 'c06fe05d59c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tasks', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tasks', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tasks', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tasks', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
