"""add roles and permissions tables

Revision ID: edd58b3dca22
Revises: 5d52bba129d8
Create Date: 2026-02-27 15:36:09.213849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session
from models.role import Role, Permission
from models.user import User

# revision identifiers, used by Alembic.
revision: str = 'edd58b3dca22'
down_revision: Union[str, Sequence[str], None] = '5d52bba129d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Create default permissions
    op.execute("INSERT INTO permissions (name) VALUES ('create_project') ON CONFLICT DO NOTHING;")
    op.execute("INSERT INTO permissions (name) VALUES ('view_all_projects') ON CONFLICT DO NOTHING;")
    op.execute("INSERT INTO permissions (name) VALUES ('update_project') ON CONFLICT DO NOTHING;")
    op.execute("INSERT INTO permissions (name) VALUES ('delete_project') ON CONFLICT DO NOTHING;")
    
    # 2. Create default roles
    op.execute("INSERT INTO roles (name) VALUES ('user') ON CONFLICT DO NOTHING;")
    op.execute("INSERT INTO roles (name) VALUES ('admin') ON CONFLICT DO NOTHING;")
    
    # 3. Assign permissions to roles (role_permissions table)
    # You may need the IDs of the roles and permissions:
    op.execute("""
        INSERT INTO role_permissions (role_id, permission_id)
        SELECT r.id, p.id
        FROM roles r, permissions p
        WHERE r.name = 'user' AND p.name = 'create_project'
        ON CONFLICT DO NOTHING;
    """)
    op.execute("""
        INSERT INTO role_permissions (role_id, permission_id)
        SELECT r.id, p.id
        FROM roles r, permissions p
        WHERE r.name = 'admin' AND p.name IN ('create_project', 'view_all_projects', 'update_project', 'delete_project')
        ON CONFLICT DO NOTHING;
    """)
    
    # 4. Assign default role to existing users
    op.execute("""
        UPDATE users
        SET role_id = (SELECT id FROM roles WHERE name='user')
        WHERE role_id IS NULL;
    """)
    
    # 5. Make role_id NOT NULL
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    
    # 6. Ensure permissions.name is NOT NULL
    op.alter_column('permissions', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('permissions', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
