"""add tenant model and tenant_id

Revision ID: fbdae855c409
Revises: 0c2306024ccf
Create Date: 2026-03-27 16:09:01.266473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbdae855c409'
down_revision: Union[str, Sequence[str], None] = '0c2306024ccf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_table('tenants',
#     sa.Column('id', sa.Integer(), nullable=False),
#     sa.Column('name', sa.String(), nullable=False),
#     sa.PrimaryKeyConstraint('id'),
#     sa.UniqueConstraint('name')
#     )
#     op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
#     op.add_column('users', sa.Column('tenant_id', sa.Integer(), nullable=True))
#     op.create_foreign_key(None, 'users', 'tenants', ['tenant_id'], ['id'])
#     # ### end Alembic commands ###


def upgrade() -> None:
    # 1. Create tenants table
    op.create_table(
        'tenants',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )

    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)

    # 2. Add tenant_id as nullable FIRST
    op.add_column('users', sa.Column('tenant_id', sa.Integer(), nullable=True))

    # 3. Create default tenant
    op.execute("INSERT INTO tenants (name) VALUES ('Default Tenant')")

    # 4. Assign all existing users to this tenant
    op.execute("""
        UPDATE users
        SET tenant_id = (SELECT id FROM tenants LIMIT 1)
    """)

    # 5. Make tenant_id NOT NULL
    op.alter_column('users', 'tenant_id', nullable=False)

    # 6. Add foreign key
    op.create_foreign_key(
        'fk_users_tenant_id',
        'users',
        'tenants',
        ['tenant_id'],
        ['id']
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'tenant_id')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
